# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
default_stages: [commit]
repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-toml
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus, --keep-runtime-typing]
-   repo: https://github.com/hakancelik96/unimport
    rev: 1.0.0
    hooks:
    -   id: unimport
        args: [--remove, --include-star-import, --ignore-init, --gitignore]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-use-fstring
        -   flake8-tidy-imports
        -   flake8-comprehensions
        -   flake8-bugbear
        -   flake8-print
        -   flake8-debugger
        -   flake8-simplify
        -   flake8-return
        -   flake8-no-pep420
        -   flake8-tuple
